apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    app: {{ template "pipelines.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "pipelines.name" . }}-{{ .Values.application.app_name }}
  namespace: {{ .Values.global.namespace }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.pipeline.source_repo_url }}
      ref: {{ .Values.pipeline.source_repo_ref }}
    contextDir: {{ .Values.pipeline.source_context_dir }}
  triggers:
    - type: GitHub
      github:
        secret: {{ .Values.application.repo_webhook_secret }}
    - type: Generic
      generic:
        secret: {{ .Values.application.repo_webhook_secret }}
  runPolicy: Serial
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: {{ .Values.pipeline.file_name }}
      env:
      - name: "APP_NAME"
        value: "{{ .Values.application.app_name }}"
      - name: "APP_DEV_NAMESPACE"
        value: "{{ .Values.application.app_dev_namespace }}"
      - name: "HELM_CHART"
        value: "https://nexus-{{ .Values.global.namespace }}.apps.{{ .Values.global.cluster_url }}{{ .Values.application.helm_chart }}"
      - name: "NEXUS_REPO"
        value: "{{ .Values.application.nexus_repo_prefix }}.{{ .Values.global.cluster_url }}"
      - name: "APPLICATION_SOURCE_REPO"
        value: "{{ .Values.application.source_repo_url }}"
      - name: "APPLICATION_SOURCE_REF"
        value: "{{ .Values.application.source_repo_ref }}"
      - name: "BUILD_CONTEXT_DIR"
        value: "{{ .Values.application.source_context_dir }}"
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    application: {{ .Values.application.app_name }}
  name: {{ .Values.application.app_name }}
  namespace: {{ .Values.global.namespace }}
spec:
  output:
    to:
      kind: DockerImage
      name: "{{ .Values.application.nexus_repo_prefix }}.{{ .Values.global.cluster_url }}/tssc/{{ .Values.application.app_name }}:latest"
    pushSecret:
      name: nexus-repo
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{ .Values.application.base_image }}
    type: Source
  triggers:
  - type: Generic
    generic:
      secret: {{ .Values.application.repo_webhook_secret }}
 