apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "jenkins", "namespace": "", "kind": "DeploymentConfig"}]'
  labels:
    app: {{ template "pipelines.name" . }}
    chart: {{ template "pipelines.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "pipelines.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  source:
    type: Git
    git:
      uri: {{ .Values.pipeline.source_repo_url }}
      ref: {{ .Values.pipeline.source_repo_ref }}
    contextDir: {{ .Values.pipeline.source_context_dir }}
  triggers:
    - type: GitHub
      github:
        secret: {{ .Values.application.repo_webhook_secret }}
    - type: Generic
      generic:
        secret: {{ .Values.application.repo_webhook_secret }}
  runPolicy: Serial
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: {{ .Values.pipeline.file_name }}
      env:
      - name: "APPLICATION_SOURCE_REPO"
        value: "{{ .Values.application.source_repo_ref }}"
      - name: "APPLICATION_SOURCE_REF"
        value: "{{ .Values.application.source_repo_ref }}"
      - name: "BUILD_CONTEXT_DIR"
        value: "{{ .Values.application.context_dir }}"
