apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ .Values.app_name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    {{- include "deployments.labels" . | nindent 4 }}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: "{{ .Values.app_name }}"
    weight: 100
  wildcardPolicy: None
